### ISSUE TITLE
Style objects

### ISSUE THREAD

**Issue by mrjjwright** [ryansolid/lit-dom-expressions#1]
Do style objects work yet?  Judging by the fixtures and my own code not quite.   That is fine, just curious.

https://github.com/ryansolid/lit-dom-expressions/blob/4d804166377e04f8afbddf0e94f8d225e04162e2/test/html.spec.js#L43

**Comment by ryansolid** [comment]
I didn't even notice that.. They should be working thanks for pointing it out.

**Comment by ryansolid** [comment]
So I figured it out. HyperScript and Lit versions were using `style.setProperty` instead of direct assignment. It is slightly faster that way but you need to use hyphenated string values there. I didn't realize that. So I've changed it back to Object.assign which is consistent with the JSX and React. It is interesting. Inferno uses setProperty (probably because it's faster) but does make it a bit of the odd one out. I think best to be consistent with React for something small like this.

Anyway fixed in v0.14.1 for both libraries.

**Comment by mrjjwright** [comment]
yay thanks!!
